## Site Meta ##
# The title of the website.
title: "Corrina McNevin"
# The description of the website
description: "Art Gallery"
# Keywords/tags for you site.
keywords: "lens, jeykll-lens, jekyll, theme, jekyll-theme, photography, blog, photography-blog, photo-blog"
# Your copyright message.
copyright: "Corrina McNevin"

## Site Configurations ##
# 1st heading of the site.
header: "Corrina McNevin"
# 2nd heading/sub heading of the website.
subheader: "Art"
# A description/bio of the website.
bio: "Corrina McNevin"
social:
  # Your Twitter username.
  twitter_username: ""
  # Your Facebook username.
  facebook_username: ""
  # Your Instagram username.
  instagram_username: ""
  # GitHub username.
  github_username: ""
  # Your email address.
  email: ""

## Gallery Configuration ##
# If you modify this, also modify the `default.scope.path` key below.
gallery_dir: "gallery"
# Any valid value of "background-position" CSS attribute.
image_position: "left center"

piano:
  - name: “Venetian Boat Song” Op. 30 No. 6
    composer: F. Mendelssohn
    video: https://www.youtube.com/embed/6rKx2qPSyfE
    thumbnail: piano/Venetian_Boat_Song.png
  - name: To a Wild Rose
    composer: Edward MacDowell
    video: https://www.youtube.com/embed/em6i1zrDTa0
    thumbnail: piano/To_a_Wild_Rose.png
  - name: Italian Song
    composer: Tchaikovsky
    video: https://www.youtube.com/embed/OcOPRBlRJQU
    thumbnail: piano/Italian_Song.png
  - name: Two Bourees
    composer: Bach
    video: https://www.youtube.com/embed/oqhaBabIPTU
    thumbnail: piano/Two_Bourees.png
  - name: Viennese Sonatina
    composer: Mozart
    video: https://www.youtube.com/embed/6IHGqhI1_Qc
    thumbnail: piano/Viennese_Sonatina.png

## Jekyll Configuration ##
defaults:
 - scope:
    # Should be same as the `gallery_dir` key above.
    path: "gallery"
   values:
    image: true
